apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-service-v2
  labels:
    app: helloworld-service
    version: "2.0"
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-service
      version: "2.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: helloworld-service
        version: "2.0"
        serving: "true"
        visualize: "true"
    spec:
      containers:
      - name: helloworld-service
        image: registry.cn-hangzhou.aliyuncs.com/niuyandong/istio-demo:0.0.2
        ports:
        - name: http
          containerPort: 8080